#autor: ing Oscar Rangel
@stories
  Feature: Academy Choucair
    As a user, I want to learn how to automate in screamplay at the Choucair Academy with the automation course
  @scenario1
  Scenario: Search for a automation course
    Given than oscar wants to learn automation at the academy Choucair

      | strUser    |  strPassword        |
      | <strUser>  |  <strPassword>      |

    When he search for the course on the choucair academy platforms

      | strCourse                   |
      | <strCourse >                |

    Then he finds the course called

      | strCurso                   |
      | <strCurso>                 |

    Example:
    | strUser    |  strPassword        | strCourse                |
    | rpenaa     |  febrero.2020       | Metodologia Bancolombia  |